cosmetic changes to readme.md file
chorvick/v pull request #29
Opened 2021-04-09 03:24 UTC by chorvick

added clickable link to application and minor cosmetic changes for easier reading

2021-04-09 18:05 UTC, SteveGekas requested changes
Try tabbing what I wrote and then push the Readme again. That should work

2021-04-09 19:18 UTC, chorvick commented
I am satisfied with this pull request as is. Currently the readme.md  is not readable. You have to scroll a box to the right in multiple places to see the text. In addition there is no clickable link to the deployed application. Also our github profiles are clickable. This pull request fixes all of these issues. If either of you disagree with what I propose then I hope someone will write some changes to what we have now and do their own pull request.

2021-04-10 00:07 UTC, flieckster approved these changes

2021-04-10 00:08 UTC, flieckster approved these changes

2021-04-10 00:09 UTC, flieckster approved these changes

2021-04-10 00:10 UTC, SteveGekas approved these changes

2021-04-10 00:10 UTC, merged